name: CI

on:
  pull_request:
    branches: [master, main]

  push:
    branches: [master, main]

concurrency:
  group: {% raw %}${{ github.head_ref || github.run_id }}{% endraw %}
  cancel-in-progress: true

{% if dkcutter.useEnvValidator -%}

env:
  SKIP_ENV_VALIDATION: true

{% endif -%}

jobs:
  lint-styles:
    name: Lint Styles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
{% if dkcutter.pkgManager == 'bun' %}
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
{% else -%}
{% if dkcutter.pkgManager == 'pnpm' %}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
{% endif %}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: {{ dkcutter.pkgManager }}
          node-version: 18
{% endif %}
      - name: Install dependencies
        run: {{ dkcutter._ciInstall }}

      - name: Running lint
{%- if not ['pnpm', 'yarn'].includes(dkcutter.pkgManager) %}
        run: {{ dkcutter.pkgManager }} run lint
{%- else %}
        run: {{ dkcutter.pkgManager }} lint
{%- endif %}
{% if dkcutter.useCommitlint %}
  lint-commits:
    name: Lint Commits
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
{% endif -%}