# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - update

  # Update npm packages
  - package-ecosystem: npm
    directory: /
    groups:
      {%- if not dkcutter.useLinters %}
      next:
        patterns:
          - next
          - eslint-config-next
      {%- endif %}
      definitely-typed:
        patterns:
          - "@types*"
        update-types:
          - minor
          - patch
      {%- if dkcutter.database == 'prisma' %}
      prisma:
        patterns:
          - "@prisma*"
          - prisma
      {%- endif %}
      {%- if dkcutter.database == 'prisma' and dkcutter.authProvider == 'nextAuth' %}
      next-auth:
        patterns:
          - "@next-auth*"
          - next-auth
      {%- endif %}
      {%- if dkcutter.useCommitlint %}
      commitlint:
        patterns:
          - "@commitlint*"
      {%- endif %}
    ignore:
      - dependency-name: "@types*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
    labels:
      - update
