# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Update npm packages
  - package-ecosystem: npm
    directory: /
    groups:
      definitely-typed:
        patterns:
          - "@types*"
        update-types:
          - minor
          - patch
      {%- if dkcutter.database == "prisma" %}
      prisma:
        patterns:
          - "@prisma*"
          - prisma
      {%- endif %}
      {%- if dkcutter.database == "prisma" and dkcutter.authProvider == "nextAuth" %}
      next-auth:
        patterns:
          - "@next-auth*"
          - next-auth
      {%- endif %}
      {%- if dkcutter.useCommitlint %}
      commitlint:
        patterns:
          - "@commitlint*"
      {%- endif %}
    schedule:
      interval: daily
